version: '3'

tasks:
  build:
    desc: Build the circle-to-task binary
    cmds:
      - go build -o circle-to-task .
    sources:
      - "*.go"
      - go.mod
      - go.sum
    generates:
      - circle-to-task

  test:
    desc: Test the converter with example config
    deps: [build]
    cmds:
      - ./circle-to-task -input examples/input-config.yml -output examples/output
      - echo "✅ Test successful"
      - echo "📁 Check examples/output/ for generated files"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f circle-to-task
      - rm -rf examples/output

  dev:
    desc: Build and test in one command
    deps: [clean, build, test]
    cmds:
      - echo "🚀 Try it yourself:"
      - echo "   ./circle-to-task -input <your-config.yml> -output <output-dir>"

  install-task:
    desc: Install go-task if not present
    cmds:
      - |
        if ! command -v task &> /dev/null; then
          echo "Installing go-task..."
          go install github.com/go-task/task/v3/cmd/task@latest
        else
          echo "✅ go-task already installed"
        fi
    status:
      - command -v task

  install:
    desc: Install circle-to-task CLI globally (latest version)
    cmds:
      - go install github.com/nichecode/circle-to-task@latest
      - echo "✅ circle-to-task@latest installed globally"
      - echo "You can now run 'circle-to-task' from anywhere"

  install-version:
    desc: Install specific version of circle-to-task CLI (use VERSION=v0.3.0)
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "❌ Please specify VERSION: task install-version VERSION=v0.3.0"
          exit 1
        fi
      - go install github.com/nichecode/circle-to-task@{{.VERSION}}
      - echo "✅ circle-to-task@{{.VERSION}} installed globally"
      - echo "You can now run 'circle-to-task' from anywhere"

  version:
    desc: Show current version and available tags
    cmds:
      - echo "🏷️ Available versions:"
      - git tag --sort=-version:refname | head -10 || echo "No tags found"
      - echo ""
      - echo "📦 Install latest{{":"}} task install"
      - echo "📦 Install specific{{":"}} task install-version VERSION=v0.3.0"

  help:
    desc: Show available tasks
    cmds:
      - task --list
