version: "2.1"
jobs:
    build:
        executor: node-executor
        steps:
            - run: task build
        parameters:
            node_version:
                default: "16"
                type: string
    deploy-staging:
        executor: node-executor
        steps:
            - run: task deploy-staging
    test:
        executor: node-executor
        steps:
            - run: task test
workflows:
    build-test-deploy:
        jobs:
            - build:
                node_version: "18"
            - test:
                requires:
                    - build
            - deploy-staging:
                requires:
                    - test
    version: 2
executors:
    node-executor:
        docker:
            - image: node:16
        environment:
            NODE_ENV: production
